<x-layout title="course"><div class="hero"><div><div class="eyebrow">{{ $offering->semester->name }} · {{ $offering->course->code }}</div><h1>{{ $offering->title }}</h1><p>{{ $offering->instructor->name }}</p></div><x-status :value="$enrollment->status" /></div>
<div class="grid two"><section class="panel"><h2><x-t k="details" /></h2><p>{{ $offering->course->description }}</p><p><x-t k="group" />: {{ $enrollment->group?->name }}</p><div class="access-summary"><strong>{{ $remainingFree }}</strong><span><x-t k="remaining_free" /></span><x-status :value="$accessSource ? 'access_available' : 'payment_required'" /></div><hr class="divider"><h3><x-t k="group_history" /></h3>@foreach($enrollment->memberships as $membership)<p class="muted">{{ $membership->group->name }} · {{ $membership->starts_at->timezone($offering->timezone)->format('Y-m-d') }} — @if($membership->ends_at){{ $membership->ends_at->timezone($offering->timezone)->format('Y-m-d') }}@else<x-t k="present" />@endif</p>@endforeach
@if($enrollment->status === 'enrolled' && $offering->status === 'open' && $offering->groups->whereNull('archived_at')->count() > 1)<details><summary><x-t k="request_transfer" /></summary><form method="POST" action="{{ route('student.transfer',$enrollment) }}" class="stack">@csrf<x-select name="group_id" label="group" required>@foreach($offering->groups->whereNull('archived_at')->where('id','!=',$enrollment->group_id) as $group)<option value="{{ $group->id }}">{{ $group->name }}</option>@endforeach</x-select><x-field name="reason" required maxlength="500" /><button class="primary"><x-t k="request_transfer" /></button></form></details>@endif
@foreach($enrollment->transferRequests as $transfer)<p class="muted">{{ $transfer->group->name }} · <x-status :value="$transfer->status" /></p>@endforeach
</section>
<section class="panel"><h2><x-t k="class_code" /></h2><p class="muted"><x-t k="class_code_hint" /></p><form method="POST" action="{{ route('attendance.code') }}" class="stack">@csrf<x-field name="code" label="short_code" required minlength="6" maxlength="6" dir="ltr" autocomplete="off" /><button class="primary"><x-t k="continue_checkin" /></button></form></section></div>
<section class="panel"><h2><x-t k="published_schedule" /></h2><div class="grid two">@forelse($sessions as $session)<article class="card"><div class="row between"><strong>{{ $session->lesson->title }}</strong><x-status :value="$session->status" /></div><p>{{ $session->scheduled_start_at->timezone($offering->timezone)->locale(app()->getLocale())->translatedFormat('l, Y-m-d H:i') }}</p><p class="muted">{{ $session->group->name }} · {{ $session->location ?: __('ui.location_not_set') }}</p></article>@empty<p class="muted"><x-t k="no_published_sessions" /></p>@endforelse</div></section>
<section class="panel"><h2><x-t k="attendance_history" /></h2>@forelse($enrollment->attendances as $attendance)<div class="list-item row between"><span>{{ $attendance->lesson->title }} · {{ $attendance->session->scheduled_start_at->timezone($offering->timezone)->format('Y-m-d') }}</span><x-status :value="$attendance->status" /></div>@empty<p class="muted"><x-t k="no_attendance" /></p>@endforelse</section>
</x-layout>
