<x-layout title="class_session">
<div class="hero"><div><div class="eyebrow">{{ $classSession->offering->title }} · {{ $classSession->group->name }}</div><h1>{{ $classSession->lesson->title }}</h1><p>{{ $classSession->scheduled_start_at->timezone($classSession->timezone)->format('Y-m-d H:i') }} — {{ $classSession->scheduled_end_at->timezone($classSession->timezone)->format('H:i') }} · {{ $classSession->timezone }}</p></div><x-status :value="$classSession->status" /></div>
<div class="row mb-4"><a class="button secondary" href="{{ route('instructor.schedule',['week'=>$classSession->scheduled_start_at->timezone($classSession->timezone)->toDateString()]) }}"><x-t k="back_schedule" /></a>@if(in_array($classSession->status,['published','in_progress']))<a class="button" href="{{ route('instructor.sessions.qr',$classSession) }}"><x-t k="show_qr" /></a>@endif</div>
<div class="grid two"><section class="panel"><h2><x-t k="session_actions" /></h2>
@if(!in_array($classSession->status,['completed','cancelled']))<details><summary><x-t k="reschedule" /></summary><form method="POST" action="{{ route('instructor.sessions.update',$classSession) }}" class="stack">@csrf @method('PUT')<x-select name="group_id" label="group">@foreach($classSession->offering->groups->whereNull('archived_at') as $group)<option value="{{ $group->id }}" @selected($group->id===$classSession->group_id)>{{ $group->name }}</option>@endforeach</x-select><x-select name="lesson_id" label="lesson">@foreach($classSession->offering->lessons->whereNull('archived_at') as $lesson)<option value="{{ $lesson->id }}" @selected($lesson->id===$classSession->lesson_id)>{{ $lesson->position }}. {{ $lesson->title }}</option>@endforeach</x-select><x-field name="scheduled_start" type="datetime-local" :value="$classSession->scheduled_start_at->timezone($classSession->timezone)->format('Y-m-d\TH:i')" required /><x-field name="scheduled_end" type="datetime-local" :value="$classSession->scheduled_end_at->timezone($classSession->timezone)->format('Y-m-d\TH:i')" required /><x-field name="location" :value="$classSession->location" /><x-field name="reason" required /><x-field name="conflict_override_reason" /><button class="primary"><x-t k="save" /></button></form></details>
<form method="POST" action="{{ route('instructor.sessions.transition',$classSession) }}" class="stack mt-3">@csrf<x-select name="action" label="action">@if($classSession->status==='published')<option value="start">{{ __('ui.start_class') }}</option>@endif @if($classSession->status==='in_progress')<option value="complete">{{ __('ui.complete_class') }}</option>@endif @if(in_array($classSession->status,['draft','published']))<option value="cancel">{{ __('ui.cancel_class') }}</option>@endif @if(in_array($classSession->status,['published','in_progress']))<option value="close_attendance">{{ __('ui.close_attendance') }}</option>@endif</x-select><x-field name="reason" required /><button class="secondary"><x-t k="apply_action" /></button></form>@endif
</section><section class="panel"><h2><x-t k="attendance_timing" /></h2><p><x-t k="opens" />: <bdi>{{ $classSession->attendance_opens_at->timezone($classSession->timezone)->format('Y-m-d H:i') }}</bdi></p><p><x-t k="late_after" />: <bdi>{{ $classSession->late_after_at->timezone($classSession->timezone)->format('Y-m-d H:i') }}</bdi></p><p><x-t k="closes" />: <bdi>{{ $classSession->attendance_closes_at->timezone($classSession->timezone)->format('Y-m-d H:i') }}</bdi></p><p><x-t k="location" />: {{ $classSession->location ?: __('ui.location_not_set') }}</p></section></div>
<section class="panel"><h2><x-t k="roster" /></h2><div class="responsive-list">@forelse($classSession->rosterEntries as $entry)<details><summary><span>{{ $entry->enrollment->student->name }} · <bdi>{{ $entry->enrollment->student->student_code }}</bdi></span> <x-status :value="$entry->status" /></summary><form method="POST" action="{{ route('instructor.sessions.attendance.correct',$classSession) }}" class="stack">@csrf<input type="hidden" name="enrollment_id" value="{{ $entry->enrollment_id }}"><x-select name="status"><option value="present">{{ __('ui.present') }}</option><option value="late">{{ __('ui.late') }}</option><option value="absent">{{ __('ui.absent') }}</option><option value="excused">{{ __('ui.excused') }}</option><option value="void">{{ __('ui.void') }}</option></x-select><x-field name="observed_at" type="datetime-local" /><x-field name="reason" required /><x-check name="payment_exception" label="payment_exception" /><button class="primary"><x-t k="save_correction" /></button></form></details>@empty<p class="muted"><x-t k="roster_captured_at_open" /></p>@endforelse</div></section>
<section class="panel"><h2><x-t k="makeup_authorization" /></h2><form method="POST" action="{{ route('instructor.sessions.makeup',$classSession) }}" class="stack">@csrf<x-select name="enrollment_id" label="student" required>@foreach($eligibleEnrollments as $enrollment)<option value="{{ $enrollment->id }}">{{ $enrollment->student->name }} · {{ $enrollment->group->name }}</option>@endforeach</x-select><x-field name="reason" required /><button class="secondary"><x-t k="authorize_makeup" /></button></form></section>
</x-layout>
